# Generated by Django 5.0.3 on 2024-03-13 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_incidentlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='incidentlog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
